-- MySQL Script generated by MySQL Workbench
-- qui 06 nov 2025 08:16:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema friv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friv` ;
USE `friv` ;

-- -----------------------------------------------------
-- Table `friv`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`jogo` (
  `idjogo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `desenvolvedor` VARCHAR(45) NOT NULL,
  `data_lanca` DATE NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`idjogo`),
  UNIQUE INDEX `idjogo_UNIQUE` (`idjogo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `gmail` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`),
  UNIQUE INDEX `idgenero_UNIQUE` (`idgenero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`categoria_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`categoria_forun` (
  `idcategoria_forun` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idcategoria_forun`),
  UNIQUE INDEX `idcategoria_forun_UNIQUE` (`idcategoria_forun` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`topico_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`topico_forun` (
  `idtopico_forun` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `categoria_forun_idcategoria_forun1` INT NOT NULL,
  `jogo_idjogo1` INT NOT NULL,
  PRIMARY KEY (`idtopico_forun`),
  INDEX `fk_topico_forun_categoria_forun1_idx` (`categoria_forun_idcategoria_forun1` ASC) VISIBLE,
  INDEX `fk_topico_forun_jogo1_idx` (`jogo_idjogo1` ASC) VISIBLE,
  UNIQUE INDEX `idtopico_forun_UNIQUE` (`idtopico_forun` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_categoria_forun1`
    FOREIGN KEY (`categoria_forun_idcategoria_forun1`)
    REFERENCES `friv`.`categoria_forun` (`idcategoria_forun`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topico_forun_jogo1`
    FOREIGN KEY (`jogo_idjogo1`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`post_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`post_forun` (
  `idpost_forun` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(255) NULL,
  `usuario_idusuario` INT NOT NULL,
  `topico_forun_idtopico_forun` INT NOT NULL,
  PRIMARY KEY (`idpost_forun`, `usuario_idusuario`, `topico_forun_idtopico_forun`),
  INDEX `fk_post_forun_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_post_forun_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC) VISIBLE,
  UNIQUE INDEX `idpost_forun_UNIQUE` (`idpost_forun` ASC) VISIBLE,
  CONSTRAINT `fk_post_forun_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_forun_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun`)
    REFERENCES `friv`.`topico_forun` (`idtopico_forun`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`avaliacao_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`avaliacao_jogo` (
  `idavaliacao_jogo` INT NOT NULL AUTO_INCREMENT,
  `classificacao` TINYINT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`idavaliacao_jogo`),
  INDEX `fk_avaliacao_jogo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_avaliacao_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  UNIQUE INDEX `idavaliacao_jogo_UNIQUE` (`idavaliacao_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`histo_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`histo_jogo` (
  `idhisto_jogo` INT NOT NULL AUTO_INCREMENT,
  `tempo_ini` DATETIME NOT NULL,
  `tempo_fim` DATETIME NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idhisto_jogo`),
  INDEX `fk_histo_jogo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  UNIQUE INDEX `idhisto_jogo_UNIQUE` (`idhisto_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`conquista` (
  `idconquista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(66) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idconquista`),
  UNIQUE INDEX `idconquista_UNIQUE` (`idconquista` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`favorito` (
  `idfavorito` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`idfavorito`, `usuario_idusuario`, `jogo_idjogo`),
  INDEX `fk_favorito_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_favorito_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  UNIQUE INDEX `idfavorito_UNIQUE` (`idfavorito` ASC) VISIBLE,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`lista` (
  `idlista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `situacao` INT NOT NULL,
  `usuario_idusuario1` INT NOT NULL,
  PRIMARY KEY (`idlista`),
  INDEX `fk_lista_usuario1_idx` (`usuario_idusuario1` ASC) VISIBLE,
  UNIQUE INDEX `idlista_UNIQUE` (`idlista` ASC) VISIBLE,
  CONSTRAINT `fk_lista_usuario1`
    FOREIGN KEY (`usuario_idusuario1`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`genero_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`genero_jogo` (
  `genero_idgenero` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`genero_idgenero`, `jogo_idjogo`),
  INDEX `fk_genero_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_genero_has_jogo_genero_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_jogo_genero`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `friv`.`genero` (`idgenero`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`topico_usu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`topico_usu` (
  `topico_forun_idtopico_forun` INT NOT NULL,
  `topico_forun_jogo_idjogo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`topico_forun_idtopico_forun`, `topico_forun_jogo_idjogo`, `usuario_idusuario`),
  INDEX `fk_topico_forun_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_topico_forun_has_usuario_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC, `topico_forun_jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_has_usuario_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun`)
    REFERENCES `friv`.`topico_forun` (`idtopico_forun`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topico_forun_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`relhisto_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`relhisto_jogo` (
  `histo_jogo_idhisto_jogo` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`histo_jogo_idhisto_jogo`, `jogo_idjogo`),
  INDEX `fk_histo_jogo_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_histo_jogo_has_jogo_histo_jogo1_idx` (`histo_jogo_idhisto_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_has_jogo_histo_jogo1`
    FOREIGN KEY (`histo_jogo_idhisto_jogo`)
    REFERENCES `friv`.`histo_jogo` (`idhisto_jogo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_histo_jogo_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`conquista_usu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`conquista_usu` (
  `conquista_idconquista` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`conquista_idconquista`, `usuario_idusuario`),
  INDEX `fk_conquista_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_conquista_has_usuario_conquista1_idx` (`conquista_idconquista` ASC) VISIBLE,
  CONSTRAINT `fk_conquista_has_usuario_conquista1`
    FOREIGN KEY (`conquista_idconquista`)
    REFERENCES `friv`.`conquista` (`idconquista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conquista_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`lista_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`lista_jogo` (
  `lista_idlista` INT NOT NULL,
  `lista_usuario_idusuario` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`lista_idlista`, `lista_usuario_idusuario`, `jogo_idjogo`),
  INDEX `fk_lista_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_lista_has_jogo_lista1_idx` (`lista_idlista` ASC, `lista_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_has_jogo_lista1`
    FOREIGN KEY (`lista_idlista`)
    REFERENCES `friv`.`lista` (`idlista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lista_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`preferencia` (
  `usuario_idusuario` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `genero_idgenero`),
  INDEX `fk_usuario_has_genero_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_usuario_has_genero_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_genero_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `friv`.`genero` (`idgenero`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `criado` DATE NOT NULL,
  `post_forun_idpost_forun` INT NOT NULL,
  `post_forun_usuario_idusuario` INT NOT NULL,
  `post_forun_topico_forun_idtopico_forun` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `post_forun_idpost_forun`, `post_forun_usuario_idusuario`, `post_forun_topico_forun_idtopico_forun`),
  INDEX `fk_comentario_post_forun1_idx` (`post_forun_idpost_forun` ASC, `post_forun_usuario_idusuario` ASC, `post_forun_topico_forun_idtopico_forun` ASC) VISIBLE,
  UNIQUE INDEX `idcomentario_UNIQUE` (`idcomentario` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_post_forun1`
    FOREIGN KEY (`post_forun_idpost_forun` , `post_forun_usuario_idusuario` , `post_forun_topico_forun_idtopico_forun`)
    REFERENCES `friv`.`post_forun` (`idpost_forun` , `usuario_idusuario` , `topico_forun_idtopico_forun`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friv`.`relacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`relacionamento` (
  `idrelacionamento` INT NOT NULL AUTO_INCREMENT,
  `seguindo` INT NOT NULL,
  `seguidor` INT NOT NULL,
  PRIMARY KEY (`idrelacionamento`),
  INDEX `fk_seguidor_usuario1_idx` (`seguindo` ASC) VISIBLE,
  INDEX `fk_seguidor_usuario2_idx` (`seguidor` ASC) VISIBLE,
  UNIQUE INDEX `idrelacionamento_UNIQUE` (`idrelacionamento` ASC) VISIBLE,
  CONSTRAINT `fk_seguidor_usuario1`
    FOREIGN KEY (`seguindo`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguidor_usuario2`
    FOREIGN KEY (`seguidor`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE friv;

-- ===============================
-- INSERIR GÊNEROS
-- ===============================
INSERT INTO `friv`.`genero` (`nome`) VALUES
('Ação'), 
('Aventura'), 
('Estratégia'), 
('Quebra-cabeça'), 
('Tiro'), 
('Esportes'), 
('Corrida'), 
('RPG'), 
('Simulação'), 
('Casual'), 
('Terror'), 
('Romance'), 
('Culinária'),
('Turno'), 
('Plataforma'), 
('Hero Shooter'), 
('Luta'),
('Tower Defense'), 
('Moda'), 
('Battle Arena'), 
('Sandbox'), 
('Sobrevivência'), 
('Jump n Run'),  -- corrigido aspas e duplicação
('MMORPG');      -- removido gênero duplicado "Corrida"

-- ===============================
-- INSERIR JOGOS
-- ===============================
INSERT INTO `friv`.`jogo` (`nome`, `descricao`, `desenvolvedor`, `data_lanca`, `img`) VALUES
('Fireboy and Watergirl', 'Duo de aventura em templo com elementos de fogo e água', 'Oslo Albet', '2009-03-15', '69090216c15eb.jpg'),
('Bloons Tower Defense', 'Jogo de estratégia com macacos e balões', 'Ninja Kiwi', '2007-12-10', '6.jpg'),
('Crush the Castle', 'Jogo de física com catapultas e castelos', 'Armor Games', '2009-05-20', 'hqdefault.jpg'),
('Raze', 'Jogo de tiro em arena com soldados', 'Sky9 Games', '2011-08-30', 'raze-3_1x1.jpeg'),  -- corrigido "tio" para "tiro"
('Honkai Star Rail', 'Honkai: Star Rail é um jogo de RPG gacha 3D desenvolvido e publicado pela HoYoverse. Foi lançado para Windows e dispositivos móveis em 26 de abril de 2023; há previsão de lançamento para PlayStation 4 e 5', 'HoYolab', '2023-04-26', 'honkai-star-rail_s7q5.jpg'),
('Five Nights at Freddys 4', 'Five Nights at Freddys 4 é um jogo eletrônico independente de sobrevivência de terror em point-and-click', 'Scott Cawthon', '2015-07-23', 'fnaf4.jpg'),
('Jogo da Barbie', 'Jogo de moda da barbie', 'Mattel', '2017-07-27', 'pablo.webp'),
('Minecraft', 'Minecraft é um jogo eletrônico sandbox de sobrevivência de 2011 desenvolvido e publicado pela Mojang Studios.', 'Mojang', '2009-05-17', 'minecraft.avif'),
('Mobile Legends: Bang Bang', 'Jogo eletrônico para aparelhos móveis no estilo Multiplayer Online Battle Arena desenvolvido pela Moonton.', 'Moonton', '2016-07-14', 'mobile.jpeg'),
('Pokemon White', 'Pokémon Black Version e White Version são jogos eletrônicos de RPG lançados em 2010, desenvolvidos pela Game Freak e publicados pela The Pokémon Company e Nintendo.', 'GameFreak', '2010-09-18', 'pokblack.webp'),
('Among Us', 'Among Us é um jogo eletrônico online de sobrevivência e dedução social, desenvolvido e publicado pela InnerSloth.', 'Innersloth', '2018-06-15', 'among-us_8kks.jpg'),
('Overwatch 2', 'Overwatch 2 é um jogo eletrônico multijogador de tiro em primeira pessoa publicado e distribuído pela Blizzard Entertainment.', 'Blizzard Entertainment', '2022-10-04', 'images.png'),
('Genshin Impact', 'RPG de ação de mundo aberto gratuito que se passa no mundo de fantasia de Teyvat.', 'HoYolab', '2020-09-28', 'genshin.png'),
('Colheita Feliz', 'Simulador de fazenda em tempo real desenvolvido pela Elex e distribuído pela Mentez, popular no Orkut.', 'Elex', '2008-06-15', 'colheita.jpg'),
('Pokemon FireRed', 'Pokémon FireRed é um remake do clássico Pokémon Red, desenvolvido pela Game Freak.', 'GameFreak', '2004-01-24', 'pk.webp'),
('Rock & Roll Racing', 'Rock N Roll Racing é um jogo eletrônico de corrida e combate veicular.', 'Blizzard Entertainment', '1993-06-04', 'rocknrollRacing.jpg'),
('Blackthorne', 'Videogame de plataforma desenvolvido pela Blizzard Entertainment.', 'Interplay', '1994-09-07', 'blackthorne.webp'),
('Metal Warriors', 'Jogo eletrônico de ação e plataforma desenvolvido pela LucasArts e publicado pela Konami.', 'LucasArts', '1995-04-07', 'maxresdefault.jpg'),
('Dragon Ball: Advanced Adventure', 'Jogo eletrônico baseado em Dragon Ball lançado para Game Boy Advance.', 'Dimps', '2004-11-18', 'dragon-ball-gba.jpg'),
('Biker Mice from Mars', 'Videogame de corrida lançado pela Konami para SNES.', 'Konami', '1994-11-01', 'biker-mice-from-mars--24160.jpg'),  -- corrigido data
('Pokemon Sapphire', 'Pokémon Ruby e Sapphire representam a terceira geração da série.', 'GameFreak', '2002-11-21', 'SI_GBA_PokemonSapphire_enGB_image1600w.jpg'),
('World of Warcraft', 'MMORPG desenvolvido e distribuído pela Blizzard Entertainment.', 'Blizzard Entertainment', '2004-11-23', 'WoW_Box_Art1.jpg'),
('The Witcher III', 'Você é Geralt de Rívia, um bruxo em busca de Ciri, a Criança da Profecia.', 'CD PROJEKT RED', '2015-05-18', 'wither3.avif'),
('Baldurs Gate III', 'RPG baseado em Dungeons & Dragons desenvolvido pela Larian Studios.', 'Larian Studios', '2023-08-03', 'badosgat3.avif'),
('No Mans Sky', 'Jogo de exploração e sobrevivência em universo gerado proceduralmente.', 'Hello Games', '2016-08-12', 'nomansky.jpeg');

-- ===============================
-- INSERIR RELAÇÃO GÊNERO_JOGO
-- ===============================
INSERT INTO `friv`.`genero_jogo` (`genero_idgenero`, `jogo_idjogo`) VALUES
(2, 1), 
(18, 2), 
(3, 2), 
(4, 3), 
(1, 4), 
(5, 4),
(8, 5), 
(14, 5), 
(11, 6), 
(19, 7),
(21, 8), 
(20, 9), 
(8, 10), 
(22, 11), 
(16, 12), 
(8, 13), 
(9, 14),
(8, 15), 
(23, 16), 
(24, 17), 
(1, 18), 
(17, 19), 
(23, 20),
(8, 21), 
(24, 22), 
(8, 23), 
(8, 24), 
(22, 25); 

-- ===============================
-- INSERIR USUÁRIOS
-- ===============================
INSERT INTO `friv`.`usuario` (`nome`, `gmail`, `senha`, `foto`, `tipo`) VALUES
('João Silva', 'joao.silva@gmail.com', '$2y$10$Fp35ITV/u9vfPRHA.7EhSO/RRyMmF4.c.uVu7WnmD/DP/YbNhSVX', '690c79a9a69c6.jpeg', 'c'),
('Maria Santos', 'maria.santos@gmail.com', '$2y$10$rQF3rE/QYlbvs37y4k5K8OZ1p3mmwQyhdI7frnZe57YSfFX41JeG.', '6908f4b3d6503.jpg', 'c'),
('Pedro Costa', 'pedro.costa@gmail.com', '$2y$10$92IXUNpkjO0rOS5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '690c7a469304f.webp', 'c'),
('Pablo (adm)', 'adm@gmail.com', '$2y$10$9AZ8LwR6/YizFQljcev/h.EAYu7cPL0CpNvKGeFNZbk883VCaXxSq', '6908f25f7ac7a.jpeg', 'A'),
('Lunna', 'lunna@gmail.com', '$2y$10$vkLZem6D2KPu8aYqrqjUKuiA8/wfafudsV9vRRaZipFQHHGehznZu', '690394dade1b5.png', 'c'),
('Kamilinha', 'kami@gmail.com', '$2y$10$RDiKVRmN2a39gIJoDMjXNOtixdqYMFBkHfhVd/nmbHDZnqVHlvjry', '6908f6fd3ca77.jpg', 'c'),
('Italo', 'italo@gmail.com', '$2y$10$qfKMDzjTInKefhdkDvidaeWewOViNy2dnZG/9gWNdgZfE246MIdHO', 'italo.jpg', 'A'),
('Kauã', 'kaua@gmail.com', '$2y$10$qfKMDzjTInKefhdkDvidaeWewOViNy2dnZG/9gWNdgZfE246MIdHO', 'kaua.jpeg', 'A'),
('Luna', 'luna@gmail.com', '$2y$10$qfKMDzjTInKefhdkDvidaeWewOViNy2dnZG/9gWNdgZfE246MIdHO', 'lunna.jpg', 'A'),
('Lucas', 'lucas@gmail.com', '$2y$10$qfKMDzjTInKefhdkDvidaeWewOViNy2dnZG/9gWNdgZfE246MIdHO', 'wither3.jpg', 'A');

-- ===============================
-- INSERIR PREFERÊNCIAS
-- ===============================
INSERT INTO `friv`.`preferencia` (`usuario_idusuario`, `genero_idgenero`) VALUES
(1, 1),
(1, 2),
(2, 4),
(2, 9),
(3, 5),
(3, 3);

-- ===============================
-- INSERIR CONQUISTAS
-- ===============================
INSERT INTO `friv`.`conquista` (`nome`, `descricao`) VALUES
('Primeiros Passos', 'Complete o primeiro nível de qualquer jogo'),
('Viciado', 'Jogue por mais de 10 horas no total'),
('Mestre dos Puzzles', 'Complete 50 quebra-cabeças'),
('Estrategista', 'Vença 20 jogos de estratégia'),
('Social', 'Comente em 10 tópicos diferentes');

INSERT INTO `friv`.`conquista_usu` (`conquista_idconquista`, `usuario_idusuario`) VALUES
(1, 1),
(1, 2),
(1, 3),
(3, 2),
(4, 3);

-- ===============================
-- INSERIR FAVORITOS
-- ===============================
INSERT INTO `friv`.`favorito` (`usuario_idusuario`, `jogo_idjogo`) VALUES
(1, 4),
(1, 5),
(2, 1),
(2, 3),
(3, 2),
(3, 4);

-- ===============================
-- INSERIR LISTAS
-- ===============================
INSERT INTO `friv`.`lista` (`nome`, `descricao`, `situacao`, `usuario_idusuario1`) VALUES
('Para jogar depois', 'Jogos que quero experimentar', 1, 1),
('Melhores jogos', 'Meus favoritos de todos os tempos', 1, 2),
('Desafios difíceis', 'Jogos que preciso terminar', 0, 3);

-- ===============================
-- INSERIR JOGOS NAS LISTAS
-- ===============================
INSERT INTO `friv`.`lista_jogo` (`lista_idlista`, `jogo_idjogo`) VALUES
(1, 2),
(1, 3),
(2, 1),
(3, 4),
(3, 5);

-- ===============================
-- INSERIR HISTÓRICO
-- ===============================
INSERT INTO `friv`.`histo_jogo` (`tempo_ini`, `tempo_fim`, `usuario_idusuario`) VALUES
('2024-08-01 14:30:00', '2024-08-01 15:45:00', 1),
('2024-08-02 10:15:00', '2024-08-02 11:30:00', 2),
('2024-08-03 16:00:00', '2024-08-03 18:20:00', 3),
('2024-08-04 09:00:00', '2024-08-04 10:30:00', 1);

INSERT INTO `friv`.`relhisto_jogo` (`histo_jogo_idhisto_jogo`, `jogo_idjogo`) VALUES
(1, 4),
(2, 1),
(3, 2),
(4, 5);

-- ===============================
-- INSERIR AVALIAÇÕES
-- ===============================
INSERT INTO `friv`.`avaliacao_jogo` (`classificacao`, `usuario_idusuario`, `jogo_idjogo`) VALUES
(5, 1, 4),
(4, 1, 5),
(5, 2, 1),
(3, 2, 3),
(4, 3, 2),
(5, 3, 4);

-- ===============================
-- INSERIR CATEGORIAS DE FÓRUM
-- ===============================
INSERT INTO `friv`.`categoria_forun` (`nome`, `descricao`) VALUES
('Geral', 'Discussões gerais sobre jogos'),
('Dúvidas', 'Tire suas dúvidas sobre os jogos'),
('Dicas', 'Compartilhe dicas e estratégias'),
('Bugs e Problemas', 'Reporte problemas técnicos');

-- ===============================
-- INSERIR TÓPICOS DE FÓRUM
-- ===============================
INSERT INTO `friv`.`topico_forun` (`nome`, `conteudo`, `categoria_forun_idcategoria_forun1`, `jogo_idjogo1`) VALUES
('Como passar do nível 5?', 'Estou travado no nível 5 do Fireboy, alguém tem alguma dica?', 3, 1),
('Melhor estratégia BTD', 'Qual a melhor torre para rounds avançados?', 3, 2),
('Problema com gráficos', 'O jogo está ficando muito lento no meu PC', 4, 4),
('Novo jogo anunciado!', 'Acabei de ver que sairá uma sequência!', 1, 3);

-- ===============================
-- INSERIR POSTS
-- ===============================
INSERT INTO `friv`.`post_forun` (`conteudo`, `usuario_idusuario`, `topico_forun_idtopico_forun`) VALUES
('Tenta usar mais o Watergirl nessa parte, ela é melhor para os obstáculos de água', 3, 1),
('O macaco super é o melhor, mas custa caro. Vá acumulando dinheiro!', 1, 2),
('Tenta diminuir a qualidade gráfica nas configurações', 2, 3),
('Que bom! Mal posso esperar para jogar!', 1, 4);

-- ===============================
-- INSERIR COMENTÁRIOS
-- ===============================
INSERT INTO `friv`.`comentario` (`comentario`, `criado`, `post_forun_idpost_forun`, `post_forun_usuario_idusuario`, `post_forun_topico_forun_idtopico_forun`) VALUES
('Vou tentar isso, obrigado!', '2024-08-05', 1, 3, 1),
('Funcionou perfeitamente!', '2024-08-06', 1, 3, 1),
('Valeu pela dica!', '2024-08-05', 2, 1, 2);

-- ===============================
-- INSERIR RELACIONAMENTOS
-- ===============================
INSERT INTO `friv`.`relacionamento` (`seguindo`, `seguidor`) VALUES
(2, 1),
(3, 1),
(1, 2),
(3, 2),
(1, 3);
