-- MySQL Script generated by MySQL Workbench
-- qui 12 jun 2025 14:26:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema friv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friv` DEFAULT CHARACTER SET utf8mb4 ;
USE `friv` ;

-- -----------------------------------------------------
-- Table `friv`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`jogo` (
  `idjogo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `desenvolvedor` VARCHAR(45) NOT NULL,
  `data_lanca` DATE NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idjogo`),
  UNIQUE INDEX `idjogo_UNIQUE` (`idjogo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `gmail` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` CHAR(1) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `seguindo` INT(11) NULL DEFAULT NULL,
  `seguidores` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`avaliacao_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`avaliacao_jogo` (
  `idavaliacao_jogo` INT(11) NOT NULL AUTO_INCREMENT,
  `classificacao` TINYINT(4) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `jogo_idjogo` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao_jogo`),
  UNIQUE INDEX `idavaliacao_jogo_UNIQUE` (`idavaliacao_jogo` ASC) VISIBLE,
  INDEX `fk_avaliacao_jogo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_avaliacao_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`categoria_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`categoria_forun` (
  `idcategoria_forun` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idcategoria_forun`),
  UNIQUE INDEX `idcategoria_forun_UNIQUE` (`idcategoria_forun` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`conquista` (
  `idconquista` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(66) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idconquista`),
  UNIQUE INDEX `idconquista_UNIQUE` (`idconquista` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`conquista_usu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`conquista_usu` (
  `conquista_idconquista` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`conquista_idconquista`, `usuario_idusuario`),
  INDEX `fk_conquista_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_conquista_has_usuario_conquista1_idx` (`conquista_idconquista` ASC) VISIBLE,
  CONSTRAINT `fk_conquista_has_usuario_conquista1`
    FOREIGN KEY (`conquista_idconquista`)
    REFERENCES `friv`.`conquista` (`idconquista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_conquista_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`favorito` (
  `idfavorito` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `jogo_idjogo` INT(11) NOT NULL,
  PRIMARY KEY (`idfavorito`, `usuario_idusuario`, `jogo_idjogo`),
  UNIQUE INDEX `idfavorito_UNIQUE` (`idfavorito` ASC) VISIBLE,
  INDEX `fk_favorito_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_favorito_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_favorito_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`genero` (
  `idgenero` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`),
  UNIQUE INDEX `idgenero_UNIQUE` (`idgenero` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`genero_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`genero_jogo` (
  `genero_idgenero` INT(11) NOT NULL,
  `jogo_idjogo` INT(11) NOT NULL,
  PRIMARY KEY (`genero_idgenero`, `jogo_idjogo`),
  INDEX `fk_genero_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_genero_has_jogo_genero_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_jogo_genero`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `friv`.`genero` (`idgenero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_genero_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`histo_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`histo_jogo` (
  `idhisto_jogo` INT(11) NOT NULL AUTO_INCREMENT,
  `tempo_ini` DATETIME NOT NULL,
  `tempo_fim` DATETIME NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idhisto_jogo`),
  UNIQUE INDEX `idhisto_jogo_UNIQUE` (`idhisto_jogo` ASC) VISIBLE,
  INDEX `fk_histo_jogo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`lista` (
  `idlista` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `situacao` INT(11) NOT NULL,
  `usuario_idusuario1` INT(11) NOT NULL,
  PRIMARY KEY (`idlista`),
  UNIQUE INDEX `idlista_UNIQUE` (`idlista` ASC) VISIBLE,
  INDEX `fk_lista_usuario1_idx` (`usuario_idusuario1` ASC) VISIBLE,
  CONSTRAINT `fk_lista_usuario1`
    FOREIGN KEY (`usuario_idusuario1`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`lista_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`lista_jogo` (
  `lista_idlista` INT(11) NOT NULL,
  `lista_usuario_idusuario` INT(11) NOT NULL,
  `jogo_idjogo` INT(11) NOT NULL,
  PRIMARY KEY (`lista_idlista`, `lista_usuario_idusuario`, `jogo_idjogo`),
  INDEX `fk_lista_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_lista_has_jogo_lista1_idx` (`lista_idlista` ASC, `lista_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lista_has_jogo_lista1`
    FOREIGN KEY (`lista_idlista`)
    REFERENCES `friv`.`lista` (`idlista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`topico_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`topico_forun` (
  `idtopico_forun` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `categoria_forun_idcategoria_forun1` INT(11) NOT NULL,
  `jogo_idjogo1` INT(11) NOT NULL,
  PRIMARY KEY (`idtopico_forun`),
  UNIQUE INDEX `idtopico_forun_UNIQUE` (`idtopico_forun` ASC) VISIBLE,
  INDEX `fk_topico_forun_categoria_forun1_idx` (`categoria_forun_idcategoria_forun1` ASC) VISIBLE,
  INDEX `fk_topico_forun_jogo1_idx` (`jogo_idjogo1` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_categoria_forun1`
    FOREIGN KEY (`categoria_forun_idcategoria_forun1`)
    REFERENCES `friv`.`categoria_forun` (`idcategoria_forun`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_topico_forun_jogo1`
    FOREIGN KEY (`jogo_idjogo1`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`post_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`post_forun` (
  `idpost_forun` INT(11) NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `topico_forun_idtopico_forun` INT(11) NOT NULL,
  PRIMARY KEY (`idpost_forun`, `usuario_idusuario`, `topico_forun_idtopico_forun`),
  UNIQUE INDEX `idpost_forun_UNIQUE` (`idpost_forun` ASC) VISIBLE,
  INDEX `fk_post_forun_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_post_forun_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC) VISIBLE,
  CONSTRAINT `fk_post_forun_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun`)
    REFERENCES `friv`.`topico_forun` (`idtopico_forun`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_forun_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`preferencia` (
  `usuario_idusuario` INT(11) NOT NULL,
  `genero_idgenero` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `genero_idgenero`),
  INDEX `fk_usuario_has_genero_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_usuario_has_genero_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `friv`.`genero` (`idgenero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_has_genero_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`relhisto_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`relhisto_jogo` (
  `histo_jogo_idhisto_jogo` INT(11) NOT NULL,
  `jogo_idjogo` INT(11) NOT NULL,
  PRIMARY KEY (`histo_jogo_idhisto_jogo`, `jogo_idjogo`),
  INDEX `fk_histo_jogo_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_histo_jogo_has_jogo_histo_jogo1_idx` (`histo_jogo_idhisto_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_has_jogo_histo_jogo1`
    FOREIGN KEY (`histo_jogo_idhisto_jogo`)
    REFERENCES `friv`.`histo_jogo` (`idhisto_jogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_histo_jogo_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `friv`.`jogo` (`idjogo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `friv`.`topico_usu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friv`.`topico_usu` (
  `topico_forun_idtopico_forun` INT(11) NOT NULL,
  `topico_forun_jogo_idjogo` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`topico_forun_idtopico_forun`, `topico_forun_jogo_idjogo`, `usuario_idusuario`),
  INDEX `fk_topico_forun_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_topico_forun_has_usuario_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC, `topico_forun_jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_has_usuario_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun`)
    REFERENCES `friv`.`topico_forun` (`idtopico_forun`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_topico_forun_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `friv`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
