-- MySQL Script generated by MySQL Workbench
-- qua 09 abr 2025 08:40:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jogo` (
  `idjogo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` TEXT NOT NULL,
  `desenvolvedor` VARCHAR(45) NOT NULL,
  `data_lanca` DATE NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`idjogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `gmail` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `tipo` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_forun` (
  `idcategoria_forun` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idcategoria_forun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topico_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topico_forun` (
  `idtopico_forun` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  `categoria_forun_idcategoria_forun` INT NOT NULL,
  PRIMARY KEY (`idtopico_forun`, `jogo_idjogo`, `categoria_forun_idcategoria_forun`),
  INDEX `fk_topico_forun_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_topico_forun_categoria_forun1_idx` (`categoria_forun_idcategoria_forun` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topico_forun_categoria_forun1`
    FOREIGN KEY (`categoria_forun_idcategoria_forun`)
    REFERENCES `mydb`.`categoria_forun` (`idcategoria_forun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_forun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_forun` (
  `idpost_forun` INT NOT NULL,
  `conteudo` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `topico_forun_idtopico_forun` INT NOT NULL,
  `topico_forun_jogo_idjogo` INT NOT NULL,
  `topico_forun_categoria_forun_idcategoria_forun` INT NOT NULL,
  PRIMARY KEY (`idpost_forun`, `usuario_idusuario`, `topico_forun_idtopico_forun`, `topico_forun_jogo_idjogo`, `topico_forun_categoria_forun_idcategoria_forun`),
  INDEX `fk_post_forun_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_post_forun_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC, `topico_forun_jogo_idjogo` ASC, `topico_forun_categoria_forun_idcategoria_forun` ASC) VISIBLE,
  CONSTRAINT `fk_post_forun_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_forun_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun` , `topico_forun_jogo_idjogo` , `topico_forun_categoria_forun_idcategoria_forun`)
    REFERENCES `mydb`.`topico_forun` (`idtopico_forun` , `jogo_idjogo` , `categoria_forun_idcategoria_forun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_jogo` (
  `idavaliacao_jogo` INT NOT NULL,
  `classificacao` TINYINT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idavaliacao_jogo`, `jogo_idjogo`, `usuario_idusuario`),
  INDEX `fk_avaliacao_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_avaliacao_jogo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`histo_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`histo_jogo` (
  `idhisto_jogo` INT NOT NULL,
  `tempo_ini` DATETIME NOT NULL,
  `tempo_fim` DATETIME NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_avaliacao_jogo_idavaliacao_jogo` INT NOT NULL,
  `usuario_avaliacao_jogo_jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`idhisto_jogo`, `usuario_idusuario`, `usuario_avaliacao_jogo_idavaliacao_jogo`, `usuario_avaliacao_jogo_jogo_idjogo`),
  INDEX `fk_histo_jogo_usuario1_idx` (`usuario_idusuario` ASC, `usuario_avaliacao_jogo_idavaliacao_jogo` ASC, `usuario_avaliacao_jogo_jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conquista` (
  `idconquista` INT NOT NULL,
  `nome` VARCHAR(66) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idconquista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorito` (
  `idfavorito` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`idfavorito`, `usuario_idusuario`, `jogo_idjogo`),
  INDEX `fk_favorito_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_favorito_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_personalizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista_personalizada` (
  `idlista_personalizada` INT NOT NULL,
  PRIMARY KEY (`idlista_personalizada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista` (
  `idlista` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `situacao` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idlista`, `usuario_idusuario`),
  INDEX `fk_lista_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacionamento_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacionamento_usuario` (
  `idrelacionamento_usuario` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrelacionamento_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preferencia_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preferencia_usuario` (
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`),
  CONSTRAINT `fk_preferencia_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero_has_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero_has_jogo` (
  `genero_idgenero` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`genero_idgenero`, `jogo_idjogo`),
  INDEX `fk_genero_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_genero_has_jogo_genero_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_genero_has_jogo_genero`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `mydb`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topico_forun_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topico_forun_has_usuario` (
  `topico_forun_idtopico_forun` INT NOT NULL,
  `topico_forun_jogo_idjogo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`topico_forun_idtopico_forun`, `topico_forun_jogo_idjogo`, `usuario_idusuario`),
  INDEX `fk_topico_forun_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_topico_forun_has_usuario_topico_forun1_idx` (`topico_forun_idtopico_forun` ASC, `topico_forun_jogo_idjogo` ASC) VISIBLE,
  CONSTRAINT `fk_topico_forun_has_usuario_topico_forun1`
    FOREIGN KEY (`topico_forun_idtopico_forun` , `topico_forun_jogo_idjogo`)
    REFERENCES `mydb`.`topico_forun` (`idtopico_forun` , `jogo_idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topico_forun_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`histo_jogo_has_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`histo_jogo_has_jogo` (
  `histo_jogo_idhisto_jogo` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`histo_jogo_idhisto_jogo`, `jogo_idjogo`),
  INDEX `fk_histo_jogo_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_histo_jogo_has_jogo_histo_jogo1_idx` (`histo_jogo_idhisto_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_histo_jogo_has_jogo_histo_jogo1`
    FOREIGN KEY (`histo_jogo_idhisto_jogo`)
    REFERENCES `mydb`.`histo_jogo` (`idhisto_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_histo_jogo_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conquista_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conquista_usuario` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conquista_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conquista_has_usuario` (
  `conquista_idconquista` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`conquista_idconquista`, `usuario_idusuario`),
  INDEX `fk_conquista_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_conquista_has_usuario_conquista1_idx` (`conquista_idconquista` ASC) VISIBLE,
  CONSTRAINT `fk_conquista_has_usuario_conquista1`
    FOREIGN KEY (`conquista_idconquista`)
    REFERENCES `mydb`.`conquista` (`idconquista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conquista_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_has_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista_has_jogo` (
  `lista_idlista` INT NOT NULL,
  `lista_usuario_idusuario` INT NOT NULL,
  `jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`lista_idlista`, `lista_usuario_idusuario`, `jogo_idjogo`),
  INDEX `fk_lista_has_jogo_jogo1_idx` (`jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_lista_has_jogo_lista1_idx` (`lista_idlista` ASC, `lista_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_has_jogo_lista1`
    FOREIGN KEY (`lista_idlista` , `lista_usuario_idusuario`)
    REFERENCES `mydb`.`lista` (`idlista` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_has_jogo_jogo1`
    FOREIGN KEY (`jogo_idjogo`)
    REFERENCES `mydb`.`jogo` (`idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacionamento_usuario_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacionamento_usuario_has_usuario` (
  `relacionamento_usuario_idrelacionamento_usuario` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`relacionamento_usuario_idrelacionamento_usuario`, `usuario_idusuario`),
  INDEX `fk_relacionamento_usuario_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_relacionamento_usuario_has_usuario_relacionamento_usuari_idx` (`relacionamento_usuario_idrelacionamento_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_relacionamento_usuario_has_usuario_relacionamento_usuario1`
    FOREIGN KEY (`relacionamento_usuario_idrelacionamento_usuario`)
    REFERENCES `mydb`.`relacionamento_usuario` (`idrelacionamento_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacionamento_usuario_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relacionamento_usuario_has_usuario1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relacionamento_usuario_has_usuario1` (
  `relacionamento_usuario_idrelacionamento_usuario` INT NOT NULL,
  `usuariorela_idusuario` INT NOT NULL,
  PRIMARY KEY (`relacionamento_usuario_idrelacionamento_usuario`, `usuariorela_idusuario`),
  INDEX `fk_relacionamento_usuario_has_usuario1_usuario1_idx` (`usuariorela_idusuario` ASC) VISIBLE,
  INDEX `fk_relacionamento_usuario_has_usuario1_relacionamento_usuar_idx` (`relacionamento_usuario_idrelacionamento_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_relacionamento_usuario_has_usuario1_relacionamento_usuario1`
    FOREIGN KEY (`relacionamento_usuario_idrelacionamento_usuario`)
    REFERENCES `mydb`.`relacionamento_usuario` (`idrelacionamento_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacionamento_usuario_has_usuario1_usuario1`
    FOREIGN KEY (`usuariorela_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preferencia_usuario_has_genero_has_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preferencia_usuario_has_genero_has_jogo` (
  `preferencia_usuario_usuario_idusuario` INT NOT NULL,
  `genero_has_jogo_genero_idgenero` INT NOT NULL,
  `genero_has_jogo_jogo_idjogo` INT NOT NULL,
  PRIMARY KEY (`preferencia_usuario_usuario_idusuario`, `genero_has_jogo_genero_idgenero`, `genero_has_jogo_jogo_idjogo`),
  INDEX `fk_preferencia_usuario_has_genero_has_jogo_genero_has_jogo1_idx` (`genero_has_jogo_genero_idgenero` ASC, `genero_has_jogo_jogo_idjogo` ASC) VISIBLE,
  INDEX `fk_preferencia_usuario_has_genero_has_jogo_preferencia_usua_idx` (`preferencia_usuario_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_preferencia_usuario_has_genero_has_jogo_preferencia_usuario1`
    FOREIGN KEY (`preferencia_usuario_usuario_idusuario`)
    REFERENCES `mydb`.`preferencia_usuario` (`usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferencia_usuario_has_genero_has_jogo_genero_has_jogo1`
    FOREIGN KEY (`genero_has_jogo_genero_idgenero` , `genero_has_jogo_jogo_idjogo`)
    REFERENCES `mydb`.`genero_has_jogo` (`genero_idgenero` , `jogo_idjogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
